Add Ali DNS provider
caddyserver/dnsproviders pull request #66
Opened 2019-05-23 08:15 UTC by colachg

Signed-off-by: cola <colachg@gmail.com>

2019-05-23 08:45 UTC, colachg commented
I have tested it myself, it looks good.

2019-05-23 09:57 UTC, colachg commented
I think if this was merged, we can close #47 , because I fix something of that and have tested it.

2019-05-23 14:38 UTC, mholt requested changes
Thanks! Just a minor nit before merging.

2019-05-23 14:38 UTC, mholt commented on alidns/alidns.go
> +// Package dnspod adapts the lego Ali DNS
Package alidns

2019-05-24 01:21 UTC, colachg commented on alidns/alidns.go
> +// Package dnspod adapts the lego Ali DNS
Em... sorry for my carelessness. :(

2019-05-24 03:46 UTC, mholt approved these changes

2019-05-24 03:46 UTC, merged